[build]
  command = "npm run build && cp -r public/admin dist/admin"
  publish = "dist"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
